version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $(pwd)/files:/etc/nginx/certs:ro
      - $(pwd)/vhostd:/etc/nginx/vhost.d
      - $(pwd)/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - $(pwd)/files:/etc/nginx/certs:rw
      - $(pwd)/vhostd:/etc/nginx/vhost.d
      - $(pwd)/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - $(pwd)/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=proxy.myattmx.com
      - LETSENCRYPT_HOST=proxy.myattmx.com
      - LETSENCRYPT_EMAIL=kevin@proxy.myattmx.com
    depends_on:
      - nginx-proxy
      - letsencrypt