version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $(pwd)/files:/etc/nginx/certs:ro
      - $(pwd)/vhostd:/etc/nginx/vhost.d
      - $(pwd)/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - $(pwd)/files:/etc/nginx/certs:rw
      - $(pwd)/vhostd:/etc/nginx/vhost.d
      - $(pwd)/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - $(pwd)/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=proxy.myattmx.com
      - LETSENCRYPT_HOST=proxy.myattmx.com
      - LETSENCRYPT_EMAIL=kevin@proxy.myattmx.com
    depends_on:
      - nginx-proxy
      - letsencrypt


docker run -itd --rm --network host \
--name proxy-squid
--volume /var/run/docker.sock:/tmp/docker.sock:ro \
--volume $(pwd)/certs/files:/etc/nginx/certs:ro \
--volume $(pwd)/certs/vhostd:/etc/nginx/vhost.d \
--volume $(pwd)/certs/html:/usr/share/nginx/html \
--label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
jwilder/nginx-proxy

docker run -itd --rm --network host \
-e NGINX_PROXY_CONTAINER=proxy-squid \
--volume $(pwd)/certs/files:/etc/nginx/certs:rw \
--volume $(pwd)/certs/vhostd:/etc/nginx/vhost.d \
--volume $(pwd)/certs/html:/usr/share/nginx/html \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
jrcs/letsencrypt-nginx-proxy-companion

docker run -itd --rm \
--expose "80" \
--volume $(pwd)/certs/html:/usr/share/nginx/html:ro \
-e VIRTUAL_HOST=proxy.myattmx.com \
-e LETSENCRYPT_HOST=proxy.myattmx.com \
-e LETSENCRYPT_EMAIL=kevin@proxy.myattmx.com \
nginx

docker run -it --rm --name squidlite  \
--network host \
--volume $(pwd)/cache:/var/spool/squid \
--volume $(pwd)/log:/var/log/squid \
--volume $(pwd)/etc/squid.conf:/etc/squid/squid.conf \
--volume $(pwd)/certs/files/proxy.myattmx.com/cert.pem:/etc/squid/cert.pem \
--volume $(pwd)/certs/files/proxy.myattmx.com/key.pem:/etc/squid/key.pem \
kevinzepeda/squidlite:ssl

docker run -it --rm --name squidlite  \
--network host \
--volume $(pwd)/squid/cache:/var/spool/squid \
--volume $(pwd)/squid/log:/var/log/squid \
--volume $(pwd)/squid/etc/squid.conf:/etc/squid/squid.conf \
kevinzepeda/squidlite:ssl